name: Publish

on:
  release:
    types:
      created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: |
        npm run generate --if-present
        npm run package --if-present

    - name: Deploy
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: npm run publish --if-present
